#!/usr/bin/env bash

print_info() {
  info "OS" distro
  info "Model" model
  info "Kernel" kernel
  info "Uptime" uptime
  info "Shell" shell
  info "Memory" memory
  info "Local IP" local_ip
}

kernel_shorthand="on"
distro_shorthand="off"
os_arch="on"
uptime_shorthand="off"
shell_path="off"
shell_version="on"
speed_type="bios_limit"
cpu_shorthand="off"
cpu_speed="off"
cpu_cores="off"
cpu_temp="off"
gpu_brand="off"
gpu_type="integrated"
refresh_rate="off"
gtk_shorthand="off"
gtk2="off"
gtk3="off"
public_ip_host="http://ident.me"
disk_show=('/')
disk_subtitle="mount"
song_shorthand="off"
install_time="on"
install_time_format="12h"
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="-"
block_range=(0 7)
color_blocks="off"
block_width=3
block_height=1
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=(distro)
ascii_bold="on"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=3
yoffset=0
xoffset=0
scrot="off"
scrot_cmd="auto"
scrot_dir="$HOME/Pictures/"
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"
image_host="teknik"
config_version="3.0.1"
